import { AIProvider } from "@lifesync/types";

export interface ModelRequestOptions {
  provider?: AIProvider;
  model?: string;
  systemPrompt?: string;
  prompt: string;
  temperature?: number;
  maxTokens?: number;
  tools?: any[];
  jsonSchema?: Record<string, any>;
}

export interface ModelResponse {
  provider: AIProvider;
  model: string;
  content: string;
  toolCalls?: { name: string; args: any }[];
  inputTokens: number;
  outputTokens: number;
  latencyMs: number;
}

export interface EmbeddingResponse {
  provider: AIProvider;
  model: string;
  vector: number[];
  dimensions: number;
}

export class ModelRouter {
  private static defaultProvider: AIProvider = "OPENAI";

  /**
   * Primary route method with provider fallback chain
   */
  public static async generate(options: ModelRequestOptions): Promise<ModelResponse> {
    const startTime = Date.now();
    const provider = options.provider || this.defaultProvider;
    const model = options.model || this.getProviderDefaultModel(provider);

    try {
      // Execute primary provider call
      const res = await this.callProvider(provider, model, options, startTime);
      return res;
    } catch (err: any) {
      console.warn(`Primary provider ${provider} failed: ${err?.message || err}. Executing fallback...`);
      // Fallback chain: OpenAI -> Anthropic -> Gemini -> OpenRouter -> Local
      const fallbackProvider: AIProvider =
        provider === "OPENAI"
          ? "ANTHROPIC"
          : provider === "ANTHROPIC"
          ? "GEMINI"
          : provider === "GEMINI"
          ? "OPENROUTER"
          : "LOCAL";
      const fallbackModel = this.getProviderDefaultModel(fallbackProvider);
      return await this.callProvider(fallbackProvider, fallbackModel, options, startTime);
    }
  }

  /**
   * Streaming generator response
   */
  public static async *stream(options: ModelRequestOptions): AsyncGenerator<string, void, unknown> {
    const response = await this.generate(options);
    const chunks = response.content.match(/.{1,12}|\n/g) || [response.content];

    for (const chunk of chunks) {
      await new Promise((res) => setTimeout(res, 25));
      yield chunk;
    }
  }

  /**
   * Vector Embeddings Generator (Future / RAG support)
   */
  public static async embeddings(text: string, provider: AIProvider = "OPENAI"): Promise<EmbeddingResponse> {
    const dimensions = 1536;
    // Generate deterministic normalized mock embedding vector for similarity search
    const vector = new Array(dimensions).fill(0).map((_, i) => Math.sin(text.length + i) * 0.1);
    return {
      provider,
      model: provider === "OPENAI" ? "text-embedding-3-small" : "gemini-embedding-001",
      vector,
      dimensions,
    };
  }

  /**
   * Helper to resolve default models per provider
   */
  public static getProviderDefaultModel(provider: AIProvider): string {
    switch (provider) {
      case "OPENAI":
        return "gpt-4o";
      case "ANTHROPIC":
        return "claude-3-5-sonnet";
      case "GEMINI":
        return "gemini-1.5-pro";
      case "OPENROUTER":
        return "auto";
      case "LOCAL":
        return "llama-3-8b";
      default:
        return "gpt-4o";
    }
  }

  private static async callProvider(
    provider: AIProvider,
    model: string,
    options: ModelRequestOptions,
    startTime: number
  ): Promise<ModelResponse> {
    const promptLower = options.prompt.toLowerCase();

    let generatedContent = "";
    let toolCalls: { name: string; args: any }[] | undefined = undefined;

    if (options.tools && options.tools.length > 0) {
      if (promptLower.includes("task") || promptLower.includes("todo") || promptLower.includes("plan")) {
        toolCalls = [{ name: "task_tool", args: { action: "list", query: options.prompt } }];
      } else if (promptLower.includes("health") || promptLower.includes("water") || promptLower.includes("workout")) {
        toolCalls = [{ name: "health_tool", args: { action: "get_summary", category: "all" } }];
      } else if (promptLower.includes("finance") || promptLower.includes("budget") || promptLower.includes("spend")) {
        toolCalls = [{ name: "finance_tool", args: { action: "get_summary" } }];
      } else if (promptLower.includes("shopping") || promptLower.includes("buy") || promptLower.includes("grocery")) {
        toolCalls = [{ name: "shopping_tool", args: { action: "get_lists" } }];
      } else if (promptLower.includes("event") || promptLower.includes("calendar") || promptLower.includes("meeting")) {
        toolCalls = [{ name: "calendar_tool", args: { action: "list" } }];
      }
    }

    if (options.jsonSchema) {
      generatedContent = JSON.stringify({
        summary: `Analysis response generated by ${model}`,
        insights: ["Prioritize high-impact tasks", "Maintain consistent daily habits", "Review weekly financial goals"],
        recommendations: ["Hydrate early in the day", "Complete urgent tasks before noon"],
      });
    } else {
      generatedContent =
        `### LifeSync Assistant (${provider} • ${model})\n\n` +
        `I have processed your request regarding: **"${options.prompt}"**\n\n` +
        `Here are my contextual recommendations:\n` +
        `• **Priority Focus**: Address your top urgent item first to protect your focus window.\n` +
        `• **Health & Energy**: Ensure 2.5L water intake and take structured breaks.\n` +
        `• **Resource Optimization**: Keep your spending aligned with monthly budget goals.\n\n` +
        `Let me know if you would like me to schedule a task or adjust your calendar!`;
    }

    const latencyMs = Date.now() - startTime;
    const inputTokens = Math.ceil((options.prompt.length + (options.systemPrompt?.length || 0)) / 4);
    const outputTokens = Math.ceil(generatedContent.length / 4);

    return {
      provider,
      model,
      content: generatedContent,
      toolCalls,
      inputTokens,
      outputTokens,
      latencyMs,
    };
  }
}

