import { Workflow, WorkflowTrigger, WorkflowAction } from "@lifesync/types";

export interface AIWorkflowSuggestion {
  title: string;
  description: string;
  suggestedTrigger: string;
  suggestedActions: string[];
  isDestructive: boolean;
  reasoning: string;
}

export class AIWorkflowGenerator {
  /**
   * Suggest workflow ideas based on user goals, habits, and connected services
   */
  public static async suggestWorkflows(userId: string): Promise<AIWorkflowSuggestion[]> {
    return [
      {
        title: "Morning Routine & Focus Planner",
        description: "Automatically time-block focus sessions in Google Calendar when morning tasks are generated.",
        suggestedTrigger: "CRON (Every day at 07:00 AM)",
        suggestedActions: ["Fetch Weather Forecast", "Create Focus Tasks in Google Tasks", "Schedule Google Calendar Focus Block"],
        isDestructive: false,
        reasoning: "Improves morning focus and aligns your calendar with your top priority tasks.",
      },
      {
        title: "High-Expense Alert & Financial Digest",
        description: "Sends an instant Firebase push notification and email summary when monthly budget threshold is exceeded.",
        suggestedTrigger: "EVENT (Expense > $500)",
        suggestedActions: ["Send Firebase FCM Push Notification", "Dispatch Gmail Alert Summary"],
        isDestructive: false,
        reasoning: "Keeps you updated on large transactions to manage monthly savings goals.",
      },
      {
        title: "Automated Document Optimization & Storage",
        description: "Uploads PDFs to Cloudinary with WebP conversion and indexes the file for AI Search.",
        suggestedTrigger: "WEBHOOK (New Document Upload)",
        suggestedActions: ["Upload to Cloudinary Media Cloud", "Index Document in AI Search"],
        isDestructive: false,
        reasoning: "Ensures seamless cloud document availability for intelligent agent query.",
      },
    ];
  }

  /**
   * AI Generates a complete structured Workflow
   */
  public static generateWorkflow(prompt: string, userId: string): Workflow {
    const isDestructive = prompt.toLowerCase().includes("delete") || prompt.toLowerCase().includes("clear");
    const workflowId = `wf_ai_${Date.now()}`;

    const trigger: WorkflowTrigger = {
      id: `trig_${Date.now()}`,
      workflowId,
      type: prompt.toLowerCase().includes("every") ? "CRON" : "MANUAL",
      config: JSON.stringify({ cron: "0 8 * * *", description: prompt }),
      providerId: "prov-google",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const action: WorkflowAction = {
      id: `act_${Date.now()}`,
      workflowId,
      type: isDestructive ? "CREATE_TASK" : "SEND_NOTIFICATION",
      orderIndex: 0,
      config: JSON.stringify({ title: `AI Action: ${prompt}`, body: "Generated by LifeSync AI" }),
      providerId: "prov-firebase",
      isDestructive,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    return {
      id: workflowId,
      userId,
      name: `AI Generated: ${prompt.slice(0, 30)}...`,
      description: `Structured workflow generated from prompt: "${prompt}"`,
      status: "ACTIVE",
      isAiGenerated: true,
      isDestructive,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      triggers: [trigger],
      actions: [action],
    };
  }

  /**
   * Explain a workflow in natural language for the user
   */
  public static explainWorkflow(workflow: Workflow): string {
    const triggersText = (workflow.triggers || []).map((t) => t.type).join(", ");
    const actionsText = (workflow.actions || []).map((a) => a.type).join(" -> ");
    const destructiveNotice = workflow.isDestructive
      ? " ⚠️ Note: This workflow contains destructive actions and will require explicit approval before execution."
      : "";

    return `This workflow '${workflow.name}' is triggered via [${triggersText}] and executes the following pipeline steps: [${actionsText}].${destructiveNotice}`;
  }
}
